
[connections.db_agendamentos]
dialect = "postgresql"
host = "aws-0-sa-east-1.pooler.supabase.com"
port = 5432
database = "postgres"
username = "postgres.ugmrendebqepvawooqrp"
password = "BQAT3au4RKXNiIL8"
query = {sslmode = "require"}